### ISSUE TITLE
Premium FLOOD WAIT ERROR ✓✓

### ISSUE THREAD

**Issue by MrBoss215** [Mayuri-Chan/pyrofork#72]
### Checklist

- [X] I am sure the error is coming from Pyrofork's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U git+https://github.com/Mayuri-Chan/pyrofork` and reproduced the issue using the latest development version

### Description

[ERROR/2024-06-10 00:48:32,509] pyrogram.client: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.GetFile")2024-06-10T00:48:32.510368+00:00 app[.1]: Traceback (most recent call last):2024-06-10T00:48:32.510368+00:00 app[.1]: File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/client.py", line 1007, in get_file2024-06-10T00:48:32.510369+00:00 app[.1]: r = await session.invoke(2024-06-10T00:48:32.510369+00:00 app[.1]: ^^^^^^^^^^^^^^^^^^^^^2024-06-10T00:48:32.510369+00:00 app[.1]: File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/session/session.py", line 407, in invoke2024-06-10T00:48:32.510370+00:00 ]: return await self.send(query, timeout=timeout)2024-06-10T00:48:32.510370+00:00 app[.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^2024-06-10T00:48:32.510370+00:00 app[ File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/session/session.py", line 364, in send2024-06-10T00:48:32.510371+00:00  RPCError.raise_it(result, type(data))2024-06- File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 92, in raise_it raise getattr pyrogram.errors.exceptions.flood_420.FloodPremiumWait: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.GetFile")

### Steps to reproduce

1

### Code example

```python
from Pyrogram import Client
import time

bot = Client(api_id=API, api_hash=HASH, bot_token=TOKEN)

userbot = Client(api_id=API, api_hash=HASH, string_session=SESSION)

userbot.run()
bot.run()

#sending media
@bot.on_message(filters.text)
async def media_dl_trst(client, message):
    # total_size = 300MB
    await userbot.download_media(message=message, progress=progress_for_pyrogram,progress_args=("Dᴏᴡɴʟᴏᴀᴅing...", ms, time.time()))

# path download size 30MB Why 
# Path Downloaded but error come & size downloaded 30MB BUT TOTAL Size 300MB
# Premium Flood Wait ✓
```

### Logs

```shell
[ERROR/2024-06-10 00:48:32,509] pyrogram.client: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.GetFile")2024-06-10T00:48:32.510368+00:00 app[.1]: Traceback (most recent call last):2024-06-10T00:48:32.510368+00:00 app[.1]: File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/client.py", line 1007, in get_file2024-06-10T00:48:32.510369+00:00 app[.1]: r = await session.invoke(2024-06-10T00:48:32.510369+00:00 app[.1]: ^^^^^^^^^^^^^^^^^^^^^2024-06-10T00:48:32.510369+00:00 app[.1]: File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/session/session.py", line 407, in invoke2024-06-10T00:48:32.510370+00:00 ]: return await self.send(query, timeout=timeout)2024-06-10T00:48:32.510370+00:00 app[.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^2024-06-10T00:48:32.510370+00:00 app[ File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/session/session.py", line 364, in send2024-06-10T00:48:32.510371+00:00  RPCError.raise_it(result, type(data))2024-06- File "/app/.heroku/python/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 92, in raise_it raise getattr pyrogram.errors.exceptions.flood_420.FloodPremiumWait: Telegram says: [420 FLOOD_PREMIUM_WAIT_X] - A wait of 15 seconds is required (caused by "upload.GetFile")
```

**Comment by pawanyadav** [comment]
facing same issue, i tried different account also

**Comment by FolcloreX** [comment]
Have you tried to except it?
https://pyrofork.wulan17.top/main/faq/how-to-avoid-flood-waits.html#how-to-avoid-flood-waits
